// <auto-generated />
using AccountInformationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccountInformationService.Infrastructure.Migrations
{
    [DbContext(typeof(AMDBContext))]
    partial class AMDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccountInformationService.Infrastructure.Model.ClientAccountDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountId");

                    b.Property<string>("ClientId");

                    b.Property<string>("CustodialAccountNumber");

                    b.Property<string>("CustodianId");

                    b.Property<string>("CustodianName");

                    b.Property<string>("IsClosed");

                    b.Property<string>("MarketValue");

                    b.Property<string>("ProgramId");

                    b.Property<string>("ProgramName");

                    b.Property<string>("RegisteredName");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ClientAccountDetails");
                });

            modelBuilder.Entity("AccountInformationService.Infrastructure.Model.ClientDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("ClientID");

                    b.Property<string>("ClientType");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ClientDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
